BOARD_TAG    	= uno
#ARDUINO_PORT 	= /dev/ttyUSB0
ARDUINO_PORT 	= /dev/ttyACM0
#ARDUINO_PORT 	= /dev/ttyAMA0
ARDUINO_LIBS 	=
ARDUINO_DIR  	= /usr/share/arduino
ADRMK_DIR	= /usr/share/arduino

include /usr/share/arduino/Arduino.mk
